---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: production
spec:
  encryptedData:
    postgres-password: AgAd3tq7CrV/ePmrhwTo9GNj5SKbK8YWF06KK5VOAeNRL2/Zhc5Ajeu9qWrHZ75EVaRpDM78MmRP+7vtfOqB2OCn5tm96X57MtxBcwVU4jsQberyn6LyJG5wWOd/WPjUv1xzyhcu2Hkp2SS0MqO4vfZppC8WjGR0MUWc761rczIVji/wQqRTZUvuADjd+4l0zgIoCUUlrhZhqnacE5Uaw/v2tObD0JCi9XM3U0ZqzFeVOM/2MSgb+fOvy/DLUl3uuWzhxxjNUG744R8HqpmnCNNK11iyuzk0wAZkh/qRGYYzrUMKBIz3MbdxJiOAKSKTiOWX60MNvZiseIMUhLZip14quVxWHy2W7MMajtllzji38RO8W1kaCm4lYvXtX45WOxAiaOln0LdzASDI/a61l22mO5K4ZsRkiG9pxz3/MBQSeZ4++Xc/XQ4I4F6qpQMgg8xT5NvDxKOfshuTraLfIFIkVR/4OpIuTYwrlUyaOfZQcIrePOEdr4SuQUUJNnH8gyZZi/WzEQo+gpKSbnjweS9V/LiROkFC+8ut9gnoR5lL2jvVwMAjxsNiOIskD3VM/NFb3VYh/F6vMIOxY+SAEaoCoCsrF4ImXUbGOFt9iGXD1yW8XXZybltVH91IZcPYitw9WBxzMFIcKmtiixlXROBtR3y8Aa6+08OoZTAgTv+cd2QsMHzpuX0E1a2wTM9fEi2nnU72/xx4RS8BPGEgx0oh
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: production
