---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secret
  namespace: staging
spec:
  encryptedData:
    database_url: AgCUqvD+ua7pcZSaawzprdzuGtlQ5ILJAWLgopjtyNQ4iyt4S7SGEAxFt9uAJSjQZTSEW65wp4/2cAfMMPKEBc3Ztsm2jksyG0HTKtStbRmD+bwyZSNhbcV2Rkv6Ub4JTaEl2KeZikePKWKCE0E8BYX4TBwfNSmK4+woge5sYUQZpL6GDCLbC2VGHo1+AUwuwJK5jebULVKdtiYwkWEB/0JELrw/GACE5xiaC5qDItMChW0HIuC6LF1vajY7g29kUeNqchuBC2wwEiLmSLTjvv8XMfUaLDJWVvL+1KZA4ZDbXIwY2iqOUfk+aPe3Yn1ReeVVII4GLqyiT/xspJzXBtw2valoYJcXrLKmy0hyBcf8UlYa36sXC0tRI+8vHX2s9atKoVXM7tyKyQjoN1kKUZeqZZrIb23SXYDu4k+lDyBbvoyQ5B923ikSPwKhQHsmudUEJGiaXpRvBAqZmsN9yF01zgESVzePbTg2z/4btMPXaDE30DFDk6DG8syg+KrAKHth5549XtpfLcsV2xYzNvheTStd/OeWjPAo2w2N8+YplHXzIKDL59XE0qWAdhqHLXn85qHn1oNUxZX9QvUUI3gK20fjJ42eOxsYcMSt/pUwh3eR3z3URisTTVL/I8B6oV4ojFoYiBGbXsH/WMHmo6KTcuhIYh2VOPu8gXOIOYD1uYJ7kH6ArvwjnqIi5gT1sQ/AweVdRqVMMhYb3TIa1E6i6TE9zAI7u23jPEmYvYbW+vIuikHMoc+593nRKOHZrc31mxZ0Q8x/3x+3u3azpdTMZWAW64E=
  template:
    metadata:
      creationTimestamp: null
      name: api-secret
      namespace: staging
