---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: staging
spec:
  encryptedData:
    postgres-password: AgCJ7JJ5qc4B0vy2dkqPm9c35JM6rUfRUT3FHRPzgGCGM/kkKadHnJGJILSnbe0Z4fmVOeVYd/7OZNQiWp9Xv6BDIIhn2yxTFVws5DTLnLoUcFD1YpojmgMAc1mPhujtUMVC2pTyQLJZUL5pQweem9D2vLFFUIfWUWcwcaVNomsBJgg7KoGeezwqCVqAq51h/nqFyxlg5CRN3vW768io6tgk1FNWlNwNkMTOdr9mFk8g6/L1Ibx5QpfhpKz90/qmf9AjRQG60oy80ICceiF6ddmgj8ytJCUYpEeHNYKyBTefDTEyegfIswYyIP8BpKfe2+GEHZj6blavkuFmYU1lB9js81ItT6PfGWUBALwUQAYInTrI/2lz7wSHqLFyzFPxmAulW16JNt7GPIlG5iCtB90tz8X03kxJdJDKPQFfL15mudMMjrbrlNe5Nl9yGI6F2AxWV7Gp5AhR9FMDttUjg9MY6QAw60UPGOejMrLFxMe4FHv7EV/JDxCs+r4sf/P6xiWN0Eu1p3H5eiNNc+rqBx/DcUSE6Nd/JcCcP2jksKy081pcY7SV73nZGJKAb/BCYgnlMWdw5kK8WS2H9+gWexRqdWEB3EcozfkIJRHAWKeMljP+ZDIuk5Z5K3F52Y0rcwHGr7k6wXcG4x9FrEpBj51mD/4Gy+53TSTn0Jh0jFBe1N6PUsSOFYkcjOQxaTf68lS8CaNCTzoByayjTxhayU5e
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: staging
