---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secret
  namespace: production
spec:
  encryptedData:
    database_url: AgCiyNdYeUjrCJuAVCJuj5mic0I8D9qKSF5peJ6UVCGzDTken6A9F7S773j8HaJxd2B9EyacGkqgP9xIC/rFJS0HH8MBjpNJqfiwdjI2UqzYYsbmgxMqmYkXzt/bm3sV1+igLV9+jfYMbUIFMJMRrY6DiloeDlL6nWOEMG7wQrr6OdK6QePBdx8DnfpSZll94RN4grMReu5V/6jT23z6NAaKUonCLiqdssJd+6h5z6oSLjHOdi9hsbYbUwdJnsiWw35KD3r0MmsHvf80w3KZjgroDa/80zbL0VXYslyYiJSxa4b66KBMywJrMDdxvC0rjn3VCv2llZHJtcxzdBIe7Cdi7hDc0U610rx/FelkEk6m/EhzENYlquNZ4zcC3Eawvcu/6djAQvjJCxnOhWZVMEcOjm6+y/40RjlrNR1nv+ujAoC70ar3fM1mASXdCf1VprBkn7ntf+QKNflaV9pNFujvhNN6zZQI6owcwfJyfcm9jybithwC1bCOaoPn50kPQiCGZ5sW0wCaxjSPhyYbo4vvvnciHEFTO1zWa4p3f74S2bZw86plL+6wm/pMUFTWvr1NEnTidZ909KyniJBuCM1EdfPdNDsD72voKYD8Eg3i2CqDELE8zQ50G6ZJfiJpqZ6oxbYUlRHoBc+ncN0i042/vE1JhO7/29MET6jcjgeb0suThYsX+YKrgwjQSyEL+8C9hHPD1LNkiXcEBilT+r0zDtqfwWAtQ77MO33V2DEjy8NLt+SI2n7sODCgKqvOq+oAgWOlQu6OATnV2IIz8hXQ0Y+yI/Y=
  template:
    metadata:
      creationTimestamp: null
      name: api-secret
      namespace: production
